### ISSUE TITLE
Ошибка после обновы

### ISSUE THREAD

**Issue by melles1991** [alexmon1989/russia_ddos#37]
Я не могу успеть словить ошибку так как окно сразу закрывается, ошибка связана с TCP на виндовс и ругается вроде как на файл services.py

**Comment by melles1991** [comment]
![Untitled](https://user-images.githubusercontent.com/11653464/158066319-16426f4d-9cc1-47ae-bbc3-c3f023bff8d7.png)

**Comment by balazszoli** [comment]
Traceback (most recent call last):
  File "DRipper.py", line 3, in <module>
    from ripper.services import main
  File "/home/balazszoli081/russia_ddos/ripper/services.py", line 7, in <module>
    from ripper import context, common
  File "/home/balazszoli081/russia_ddos/ripper/context.py", line 9, in <module>
    from ripper import common
  File "/home/balazszoli081/russia_ddos/ripper/common.py", line 26, in <module>
    def readfile(filename: str) -> list[str]:
TypeError: 'type' object is not subscriptable

**Comment by AlexNDRmac** [comment]
Спасибо за репорт. Уже исправили, обновление будет доступно буквально через 10 мин.

**Comment by melles1991** [comment]
> Спасибо за репорт. Уже исправили, обновление будет доступно буквально через 10 мин.

спс, закрывай
