### ISSUE TITLE
eror 

### ISSUE THREAD

**Issue by babodai** [alexmon1989/russia_ddos#59]
Traceback (most recent call last):
  File "DRipper.py", line 1, in <module>
    from ripper.services import cli
  File "/etc/russia_ddos/ripper/services.py", line 13, in <module>
    from ripper.github_updates_checker import GithubUpdatesChecker
  File "/etc/russia_ddos/ripper/github_updates_checker.py", line 9, in <module>
    class Version:
  File "/etc/russia_ddos/ripper/github_updates_checker.py", line 20, in Version
    _parts: list[int] = None
TypeError: 'type' object is not subscriptable

**Comment by knyga** [comment]
@babodai
1. What is your Python version?
2. What is the command you are trying to execute?
